services:
  #Mongo DB service | Any name that you want
  mongo_db:
    container_name: db_container #Completely optional
    image: mongo:latest
    restart: always
    #environment:
    #  - MONGO_INITDB_ROOT_USERNAME=brunomembrado
    #  - MONGO_INITDB_ROOT_PASSWORD=FzshrwA8bIQ9mAOM
    #command: [--auth]
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=mongodb://mongo_db:27017
      #- DATABASE_PASSWORD=FzshrwA8bIQ9mAOM
      #- DATABASE_USER=brunomembrado
      - PORT=8080
      - NODE_ENV=production
      - SECRET_PASSWORD=thisisthesecretandtemporarykey
      - JWT_EXPIRES_IN=30d
      - JWT_COOKIE_EXPIRES_IN=30d
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
