name: Continous integration pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  
    lint:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0   
            - uses: actions/setup-node@v2
              with:
                node-version: '16'
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Tests
              run: npm run test
    build:
      runs-on: ubuntu-20.04
      steps:
          - uses: actions/checkout@v2
            with:
              fetch-depth: 0   
          - uses: actions/setup-node@v2
            with:
              node-version: '16'
          - name: Install dependencies
            run: npm ci
          - name: Lint
            run: npm run lint
          - name: Build
            run: npm run build
    test:
      needs: [lint, build]
      runs-on: ubuntu-20.04
      steps:
          - uses: actions/checkout@v2
            with:
              fetch-depth: 0   
          - uses: actions/setup-node@v2
            with:
              node-version: '16'
          - name: Install dependencies
            run: npm ci
          - name: Lint
            run: npm run lint
          - name: Test
            run: npm test  